[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*"]

[build]
  command = "npm install --prefix netlify/functions"

[functions."gemini"]
  timeout = 30